dependencies:
- name: postgresql
  version: 11.9.13
  repository: https://charts.bitnami.com/bitnami
  condition: useDockerizedDatabase
- name: redis
  version: 10.6.13
  repository: https://helm.lco.global
  condition: redis.enabled
