# Helm chart values for Production Deployment

djangoDebug: false
saveTestMessages: false

replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

brokers:
  gcnClassicOverKafka:
    groupId: 'hermes'

hermesFrontEndBaseUrl: https://hermes.lco.global/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  hosts:
    - host: hermes.lco.global
      paths:
        - "/messages"
        - "/admin"
        - "/api"
        - "/auth"
        - "/get-csrf-token"
        - "/login-redirect"
        - "/logout-redirect"
