# Helm chart values for Development Deployment

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

hermesFrontEndBaseUrl: http://hermes-dev.lco.gtn/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-private
  hosts:
    - host: hermes-dev.lco.gtn
      paths:
        - "/messages"
        - "/api"
        - "/submit"
        - "/auth"
        - "/get-csrf-token"
        - "/login-redirect"
        - "/logout-redirect"
        - "/asdf"

