# Helm chart values for Production Deployment

djangoDebug: false
saveTestMessages: false

replicaCount: 3

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

brokers:
  gcnClassicOverKafka:
    groupId: 'hermes'
  hopskotch:
    groupId: 'hermes'

gcnEmail: circulars@gcn.nasa.gov

hermesFrontEndBaseUrl: https://hermes.lco.global/

scimma:
  authBaseUrl: https://my.hop.scimma.org/hopauth
  archiveBaseUrl: https://archive-api.dev.hop.scimma.org/
  kafkaBaseUrl: kafka://dev.hop.scimma.org/

tns:
  baseUrl: "https://www.wis-tns.org/"

gcn:
  baseUrl: "https://gcn.nasa.gov/"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "5M"
    nginx.ingress.kubernetes.io/large-client-header-buffers: 16 5M
    nginx.ingress.kubernetes.io/server-snippet: | # this is where the magic happens
      client_header_buffer_size 5M;
      large_client_header_buffers 16 5M;
  hosts:
    - host: hermes.lco.global
      paths:
        - "/static"
        - "/admin"
        - "/api"
        - "/auth"
        - "/gcn-auth"
        - "/get-csrf-token"
        - "/login-redirect"
        - "/logout-redirect"

useDockerizedDatabase: false
postgresql:
  client:
    TLSMode: "require"
  hostname: prod-hermes.cple9sjsskrf.us-west-2.rds.amazonaws.com
