# Helm chart values for Development Deployment

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

brokers:
  gcnClassicOverKafka:
    groupId: 'hermes-dev'
  hopskotch:
    groupId: 'hermes-dev'

hermesFrontEndBaseUrl: https://hermes-dev.lco.global/

gcnEmail: circulars@dev.gcn.nasa.gov

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "5M"
    nginx.ingress.kubernetes.io/large-client-header-buffers: 16 5M
    nginx.ingress.kubernetes.io/server-snippet: | # this is where the magic happens
      client_header_buffer_size 5M;
      large_client_header_buffers 16 5M;
  hosts:
    - host: hermes-dev.lco.global
      paths:
        - "/api"
        - "/admin"
        - "/auth"
        - "/gcn-auth"
        - "/static"
        - "/get-csrf-token"
        - "/login-redirect"
        - "/logout-redirect"
