# Helm chart values for Development Deployment

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

brokers:
  gcnClassicOverKafka:
    groupId: 'hermes-dev'
  hopskotch:
    groupId: 'hermes-dev'

hermesFrontEndBaseUrl: https://hermes-dev.lco.global/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  hosts:
    - host: hermes-dev.lco.global
      paths:
        - "/messages"
        - "/api"
        - "/admin"
        - "/auth"
        - "/get-csrf-token"
        - "/login-redirect"
        - "/logout-redirect"

