{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hermes.serviceAccountName" . }}
  labels:
{{ include "hermes.labels" . | indent 4 }}
{{- end -}}
