# Generated by Django 4.0.3 on 2022-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True),
        ),
    ]
