# Generated by Django 4.0.3 on 2022-04-13 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0003_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
