# Generated by Django 4.0.3 on 2022-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0004_remove_message_timestamp_message_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
