# Generated by Django 4.0.4 on 2022-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0005_alter_message_author_alter_message_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
