# Generated by Django 4.1.1 on 2022-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hermes", "0007_alter_message_author_alter_message_message_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="published",
            field=models.DateTimeField(
                null=True, verbose_name="Time Published to Stream"
            ),
        ),
    ]
