# Generated by Django 4.1.1 on 2022-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hermes", "0008_message_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="published",
            field=models.DateTimeField(
                null=True,
                verbose_name="Time Published to Stream from message metadata.",
            ),
        ),
    ]
