# Generated by Django 4.1.3 on 2022-12-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0010_nonlocalizedevent_message_message_parser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='message',
            name='submitter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_parser',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
