# Generated by Django 4.1.5 on 2023-01-24 22:27

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    Message = apps.get_model('hermes', 'Message')
    for row in Message.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0013_message_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
