# Generated by Django 4.1.7 on 2023-04-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0016_alter_message_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credential_name',
            field=models.CharField(blank=True, default='', help_text='Scimma Auth User Scram Credential name', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='credential_password',
            field=models.CharField(blank=True, default='', help_text='Scimma Auth User Scram Credential password', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='credential_pk',
            field=models.BigIntegerField(default=-1, help_text='Scimma Auth User Scram Credential primary key'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hop_user_pk',
            field=models.BigIntegerField(default=-1, help_text='Scimma Auth User primary key'),
        ),
    ]
