# Generated by Django 4.2 on 2023-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0017_profile_credential_name_profile_credential_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='combined_skymap_hash',
            field=models.UUIDField(blank=True, help_text='A UUID from an md5 hash of the raw combined skymap file contents, used to detect when the skymap has changed', null=True),
        ),
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='combined_skymap_version',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Version of the combined skymap for this event, derived from detecting a change in the raw skymap from its hash', null=True),
        ),
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='skymap_hash',
            field=models.UUIDField(blank=True, help_text='A UUID from an md5 hash of the raw skymap file contents, used to detect when the skymap has changed', null=True),
        ),
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='skymap_version',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Version of the skymap for this event, derived from detecting a change in the raw skymap from its hash', null=True),
        ),
    ]
