# Generated by Django 4.2 on 2023-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0018_nonlocalizedeventsequence_combined_skymap_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlocalizedevent',
            name='event_type',
            field=models.CharField(choices=[('GW', 'Gravitational Wave'), ('GRB', 'Gamma-ray Burst'), ('NU', 'Neutrino'), ('UNK', 'Unknown')], default='GW', help_text='The type of NonLocalizedEvent', max_length=32),
        ),
        migrations.AlterField(
            model_name='nonlocalizedevent',
            name='event_id',
            field=models.CharField(db_index=True, default='', help_text='The GraceDB event id for GW events, sometimes reffered to as TRIGGER_NUM in LVC notices. Or the Icecube runnum_eventnum for NU events', max_length=64, primary_key=True, serialize=False),
        ),
    ]
