# Generated by Django 4.2 on 2023-10-12 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hermes', '0019_nonlocalizedevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrated_app', models.CharField(choices=[('GCN', 'GCN')], default='GCN', max_length=32)),
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=2048)),
                ('expires_at', models.DateTimeField(null=True)),
                ('expires_in', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
