# Generated by Django 4.2 on 2023-10-26 23:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0020_oauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='group_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of permissions associated with this token', size=None),
        ),
    ]
