# Generated by Django 4.2 on 2024-02-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0021_oauthtoken_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tns_bot_api_token',
            field=models.CharField(blank=True, default='', help_text='TNS Bot API Token to use when submitting to TNS from this user', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='tns_bot_id',
            field=models.BigIntegerField(blank=True, default=-1, help_text='TNS Bot ID to use when submitting to TNS from this user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tns_bot_name',
            field=models.CharField(blank=True, default='', help_text='TNS Bot Name to use when submitting to TNS from this user', max_length=64),
        ),
    ]
