# Generated by Django 4.2 on 2024-03-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0022_profile_tns_bot_api_token_profile_tns_bot_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credential_pk',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hop_user_pk',
        ),
    ]
