# Generated by Django 4.2 on 2025-09-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0023_remove_profile_credential_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='retracted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether or not this message has been retracted.'),
        ),
        migrations.AddField(
            model_name='message',
            name='retracted_on',
            field=models.DateTimeField(blank=True, help_text='Date this message was retracted, or null if it has not been retracted.', null=True, verbose_name='Retracted On'),
        ),
    ]
