# Generated by Django 4.2.25 on 2025-10-30 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0024_message_retracted_message_retracted_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_parser',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='message',
            name='published',
        ),
        migrations.RemoveField(
            model_name='message',
            name='retracted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='retracted_on',
        ),
        migrations.RemoveField(
            model_name='message',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='nonlocalizedeventsequence',
            name='combined_skymap_hash',
        ),
        migrations.RemoveField(
            model_name='nonlocalizedeventsequence',
            name='combined_skymap_version',
        ),
        migrations.RemoveField(
            model_name='nonlocalizedeventsequence',
            name='skymap_hash',
        ),
        migrations.RemoveField(
            model_name='nonlocalizedeventsequence',
            name='skymap_version',
        ),
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonlocalizedeventsequence',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
