# Generated by Django 4.2.25 on 2026-03-19 05:16

import django.contrib.postgres.fields
from django.db import migrations, models
import hermes.models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0025_alter_message_options_remove_message_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_topics_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=hermes.models.get_default_topics, help_text='List of default topics to show in the UI for this user', size=None),
        ),
        migrations.AlterField(
            model_name='nonlocalizedeventsequence',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
